baseURL: "https://doeschbj.github.io/"
languageCode: "en-us"
title: "Björn Döschl"
theme: "ananke"
relativeURLs: true
canonifyURLs: true


caches:
  images:
    dir: ":cacheDir/images"

menu:
  main:
    - identifier: about
      name: About Me
      url: /about/
      weight: 1